#!/bin/python

import math
import os
import random
import re
import sys

# Complete the countSwaps function below.
def countSwaps(a):
    sumSwap = 0
    for i in range(len(a)-1): # jumlah step
        for j in range(len(a)-i-1): # rest step
            if a[j] > a[j+1]:
                swap = a[j]
                a[j] = a[j+1]
                a[j+1] = swap
                sumSwap += 1

    print "Array is sorted in " + str(sumSwap) + " swaps."
    print "First Element: " + str(a[0])
    print "Last Element: " + str(a[len(a)-1])

if __name__ == '__main__':
    n = int(raw_input())

    a = map(int, raw_input().rstrip().split())

    countSwaps(a)
