#!/bin/python

import math
import os
import random
import re
import sys

# Complete the maximumToys function below.
def maximumToys(prices, k):
    prices.sort()
    batasvalue = 0
    tempvalue = 0
    finalvalue = 0
    for i in range(len(prices)):
        if prices[i] >= k:
            #batasvalue = i
            break
        batasvalue = i+1
    
    for i in range(batasvalue):
        tempvalue += prices[i]
        #finalvalue = i+1
        if tempvalue > k:
            #finalvalue-=1
            break
        finalvalue = i+1 # menggantikan comment di atas

    return finalvalue

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = raw_input().split()

    n = int(nk[0])

    k = int(nk[1])

    prices = map(int, raw_input().rstrip().split())

    result = maximumToys(prices, k)

    fptr.write(str(result) + '\n')

    fptr.close()
